apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "caddy.fullname" . }}-caddyfile
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "caddy.labels" . | nindent 4 }}
data:
  Caddyfile: |
    {{- include "caddy.caddyfile" . | nindent 4 }}
