apiVersion: v2
name: caddy
description: Caddy ingress with WAF, TCP/UDP, CertMagic ACME (HTTP/TLS-ALPN/DNS/On-Demand), cert-manager CSI, CrowdSec, GeoIP, authentication/SSO, rate limiting and caching
type: application
version: 0.9.0
appVersion: "1.0.0"
icon: https://caddyserver.com/resources/images/caddy-circle-lock.svg

keywords:
  - caddy
  - ingress
  - waf
  - coraza
  - l4
  - crowdsec
  - authentication
  - sso
  - oauth2
  - oidc
  - on-demand-tls
  - acme
  - eab

dependencies:
  - name: redis
    version: "25.3.9"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
